### ISSUE TITLE
[flutter] (prefer) trailing_commas

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1338] opened 2019-01-03 14:38 UTC
Following-up from https://github.com/flutter/flutter-intellij/issues/2980#issuecomment-451105228, we might consider a rule that enforces the [flutter style guide suggestion](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-a-trailing-comma-for-arguments-parameters-and-list-items-but-only-if-they-each-have-their-own-line):

> Use a trailing comma for arguments, parameters, and list items, but only if they each have their own line.

Since a major motivation is to give analyzer something to hang quick-fixes from, we might consider enforcing just the first part and allowing `dartfmt` to handle line-breaks but maybe this would make the rule less useful for flutter repo committers.

@Hixie: any thoughts?

/cc @jaumard

**Comment by srawlins** [comment] 2019-01-03 15:59
FYI I have a request for `dartfmt --fix` to add support for this too: https://github.com/dart-lang/dart_style/issues/753

**Comment by a14n** [comment] 2019-01-30 20:40
I started a lint for this case and I think there should be at least 2 lints.

One to lint missing coma in the following cases (flutter code that don't use `dartfmt`)

```dart
void f(
  int p1,
  int p2
) {
  ....
}
```

An other one (really harder to do) that takes some list of params/args/elements and advices to add a trailing coma to make the formatted code (with ``dartfmt) looks better.

```dart
void f(int parameter1, int parameter2, int parameter3, int parameter4,
    int parameter5, int parameter6, int parameter7, int parameter8) {
  //
}

// after trailing coma

void f(
  int parameter1,
  int parameter2,
  int parameter3,
  int parameter4,
  int parameter5,
  int parameter6,
  int parameter7,
  int parameter8,
) {
  //
}
```

Another simpler lint could be to check trailing comas in widget trees.

**Comment by bwilkerson** [comment] 2019-01-30 20:58
For the record, I'm not convinced that the value of a lint like this would justify the cost (cognitive load for users, maintenance cost for us). How many users would be helped by having this lint? (And for how long? Seems like after a couple of days most users would learn to add commas without needing a prompt.)

That said, writing the lint should be fairly trivial. For every list you want to check, get the last element, get it's end token, and look to see whether the next token is a comma. If you only want to check lists whose elements are already on separate lines (or whose first and last elements are on different lines, or whatever) then use the tokens to get offsets and use the LineInfo to map those offsets to line numbers and compare those.

**Comment by a14n** [comment] 2019-01-30 21:13
>That said, writing the lint should be fairly trivial. For every list you want to check, get the last element, get it's end token, and look to see whether the next token is a comma. If you only want to check lists whose elements are already on separate lines (or whose first and last elements are on different lines, or whatever) then use the tokens to get offsets and use the LineInfo to map those offsets to line numbers and compare those.

That's what I did :)

There are several problems.

In the flutter codebase (that don't use `dartfmt`) a missing trailing comma don't really have a impact until someone copy-paste code to put it in a place that will use `dartfmt`. Trees will suddently be flattened if a trailing comma is missing.

In a project that uses `dartfmt` the above rule to trigger the lint couldn't be used. As my second snippet shows, `dartfmt` formats `f` on two lines. No lint will be triggered here.

**Comment by Hixie** [comment] 2019-02-01 06:16
Flutter would totally use this lint.

> Seems like after a couple of days most users would learn to add commas without needing a prompt.

I've been writing code in this style for a couple of years and I still regularly omit the comma by mistake (then hate myself when I try to add another item to the list, and the compiler and analyzer lose their mind because they can't figure out what I did wrong).

**Comment by bwilkerson** [comment] 2019-02-01 17:41
Is this a fair summary?

- In hand-formatted (Flutter) code you're using the formatting as a signal as to when a comma was intended but forgotten.

- In auto-formatted code we're not sure what the right signal is (because the intent has been lost).

It would be great to find a shared signal so that we don't need two rules, so let me ask a couple of questions.

Why are some widgets (such as `AppBar` and `Expanded`) not formatted on multiple lines? (My guess, having not looked at a lot of Flutter code) is that the widgets with children are formatted differently than widgets without children.)

Does the style of formatting arguments on multiple lines apply to anything other than widgets?

**Comment by Hixie** [comment] 2019-02-01 19:10
> I think Flutter wants a rule that users should always include a comma at the end of parameter and argument lists. Is that true?

Here are some examples where you wouldn't want a trailing comma:

```dart
  void foo(String bar) {
  }

  var bar = [1, 2, 3];

  quux(bar, baz);
```

**Comment by a14n** [comment] 2019-02-01 21:35
>Why are some widgets (such as AppBar and Expanded) not formatted on multiple lines?

My above sample (without commas for AppBar and Expanded) was code from a sample that should have used trailing commas. There are just typo that need to be fixed. So AppBar and Expanded are not exceptions.

Regarding the samples @Hixie put in its last comment. It's what I described as the logic for the first rule and what I already have implemented locally.

The second case is not only specific to Flutter. If you look at dart-lang/dart_style#753 it's related to angular. That's why I mentioned a hypothetical `@tree`.

**Comment by zanderso** [comment] 2019-09-16 16:24
@a14n If you already have a something drawn up for use case (1), I'd really like to use it. Is it possible to factor the two lints you have in mind so they can be discussed/landed separately?

**Comment by a14n** [comment] 2019-09-17 17:11
@zanderso I just pushed https://github.com/a14n/linter/commit/39c59d6ae4a8a59055024002f1ba4840292e1b5e available in https://github.com/a14n/linter/tree/prefer_trailing_commas branch

I run the lint on flutter codebase (only on `packages/flutter`) and there are 410 occurances.

**Comment by a14n** [comment] 2019-09-17 19:31
FWIW I think `prefer_trailing_commas` should live in a Flutter analyzer plugin beside all kind of formatting rules that could enforce the [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) (until a flutter formatting tool arises). Unfortunatelly it is blocked by flutter/flutter#28327

**Comment by cah4a** [comment] 2020-05-12 10:19
I think it could be useful only if list does not fit into a single line:

#### Bad:
```dart
void foo(
    String bar,
) {
   print(
      bar,
   );
}

void bar(int parameter1, int parameter2, int parameter3, int parameter4,
    int parameter5, int parameter6, int parameter7, int parameter8) {
  fn(parameter1, parameter2, parameter3, parameter4, parameter5, parameter6,
    parameter7, parameter8);
}
```

#### Good:
```dart
void foo(String bar) {
  print(bar);
}

void bar(
  int parameter1,
  int parameter2,
  int parameter3,
  int parameter4,
  int parameter5,
  int parameter6,
  int parameter7,
  int parameter8,
) {
  print([
    parameter1,
    parameter2,
    parameter3,
    parameter4,
    parameter5,
    parameter6,
    parameter7,
    parameter8,
  ]);
}
```

**Comment by nepaul** [comment] 2020-07-03 06:40
> FWIW I think `prefer_trailing_commas` should live in a Flutter analyzer plugin beside all kind of formatting rules that could enforce the [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) (until a flutter formatting tool arises). Unfortunatelly it is blocked by [flutter/flutter#28327](https://github.com/flutter/flutter/issues/28327)

Yep! 👍

**Comment by SeasonLeee** [comment] 2020-09-18 04:07
It's September 18, 2020... almost a year since this commit opened, any update?

**Comment by Galti** [comment] 2020-09-22 10:33
+

**Comment by incendial** [comment] 2020-11-17 18:43
If anyone is still interested in this rule we have implemented it in https://github.com/wrike/dart-code-metrics (along with other rules that can be useful). Any feedback is welcome.

**Comment by lauweijie** [comment] 2021-03-24 09:33
I've written a lint for this and have reproduced the test case below for discussion.

**Use trailing commas for all function calls and definitions.**

**Exception:** If the function call or definition, from the start of the function name up to the closing parenthesis, fits in a single line.

**Exception:** If the final parameter is positional (vs named) and either a function literal implemented using curly braces, a literal map, a literal set or a literal array. This exception only applies if the final parameter does not fit entirely on one line.

If I hear no objections, I'll raise a PR shortly.

```
class RequireTrailingCommaExample {
  RequireTrailingCommaExample.constructor1(Object param1, Object param2);

  RequireTrailingCommaExample.constructor2(
    Object param1,
    Object param2,
    Object param3,
  );

  RequireTrailingCommaExample.constructor3(
      Object param1, Object param2, Object param3); // LINT

  RequireTrailingCommaExample.constructor4(
    Object param1,
    Object param2, [
    Object param3 = const [
      'test',
    ],
  ]);

  RequireTrailingCommaExample.constructor5(Object param1, Object param2,
      [Object param3 = const [
        'test',
      ]]); // LINT

  void method1(Object param1, Object param2, {Object param3, Object param4}) {}

  void method2(
    Object param1,
    Object param2,
    Object param3,
    Object param4,
    Object param5,
  ) {}

  void method3(
    Object param1,
    Object param2, {
    Object param3,
    Object param4,
    Object param5,
  }) {}

  void method4(Object param1, Object param2, Object param3, Object param4,
      Object param5) {} // LINT

  void method5(Object param1, Object param2,
      {Object param3, Object param4, Object param5}) {} // LINT

  void method6(Object param1, Object param2,
      {Object param3,
      Object param4,
      Object param5,
      Object param6,
      Object param7}) {} // LINT

  void run() {
    void test(Object param1, Object param2, {Object param3}) {}

    test('fits on one line, no need trailing comma', 'test');

    test(
      'does not fit on one line, requires trailing comma',
      'test test test test test',
    );

    test('does not fit on one line, requires trailing comma',
        'test test test test test'); // LINT

    test('test', () {
      // Function literal implemented using curly braces.
    });

    test('test', () {
      // Function literal implemented using curly braces.
    }, param3: 'test'); // LINT

    test(
      'test',
      () {
        // Function literal implemented using curly braces.
      },
      param3: 'test',
    );

    test('test', 'test', param3: () {
      // Function literal implemented using curly braces.
    }); // LINT

    test(
      'test',
      'test',
      param3: () {
        // Function literal implemented using curly braces.
      },
    );

    test(
      () {
        // Function literal implemented using curly braces.
      },
      'test',
    );

    test(() {
      // Function literal implemented using curly braces.
    }, 'test'); // LINT

    test('map literal', {
      'one': 'test',
      'two': 'test',
    });

    test({
      'one': 'test',
      'two': 'test',
    }, 'map literal'); // LINT

    test('set literal', {
      'one',
      'two',
    });

    test({
      'one',
      'two',
    }, 'set literal'); // LINT

    test('list literal', [
      'one',
      'two',
    ]);

    test([
      'one',
      'two',
    ], 'list literal'); // LINT

    test(
      'no exception for set literal as it fits entirely on 1 line',
      const {'one', 'two', 'three'},
    );

    test('no exception for set literal as it fits entirely on 1 line',
        const {'one', 'two', 'three'}); // LINT

    test('exception for set literal as it spans multiple lines', const {
      'one',
      'two',
      'three',
    });

    test('exception for set literal as it spans multiple lines', const <
        AnExtremelyLongClassNameOneTwoThreeFourFiveSixSevenEightNineTen>{});

    test(
      'no exception for array literal as it fits entirely on 1 line',
      const ['one', 'two', 'three'],
    );

    test('no exception for array literal as it fits entirely on 1 line',
        const ['one', 'two', 'three']); // LINT

    test('exception for array literal as it spans multiple lines', const [
      'one',
      'two',
      'three',
    ]);

    test('exception for array literal as it spans multiple lines', const <
        AnExtremelyLongClassNameOneTwoThreeFourFiveSixSevenEightNineTen>[]);

    test(
      'no exception for map literal as it fits entirely on 1 line',
      const {'one': '1', 'two': '2', 'three': '3'},
    );

    test('no exception for map literal as it fits entirely on 1 line',
        const {'one': '1', 'two': '2', 'three': '3'}); // LINT

    test('exception for map literal as it spans multiple lines', const {
      'one': '1',
      'two': '2',
      'three': '3',
    });

    test('exception for map literal as it spans multiple lines', const <String,
        AnExtremelyLongClassNameOneTwoThreeFourFiveSixSevenEightNineTen>{});

    test(
      'no exception for function literal as it fits entirely on 1 line',
      () {},
    );

    test('no exception for function literal as it fits entirely on 1 line',
        () {}); // LINT

    assert(true);

    assert('a very very very very very very very very very long string'
        .isNotEmpty); // LINT

    assert(
      'a very very very very very very very very very long string'.isNotEmpty,
    );

    assert(false, 'a short string');

    assert(false,
        'a very very very very very very very very very long string'); // LINT

    assert(
      false,
      'a very very very very very very very very very long string',
    );
  }
}

class AnExtremelyLongClassNameOneTwoThreeFourFiveSixSevenEightNineTen {}
```

**Closed** 2021-03-26 16:26 UTC
Labels: customer: money (g3), enhancement, lint request

**Comment by jackforesightmobile** [comment] 2021-07-16 08:37
How can I use this rule in my analysis_options.yaml file? It doesn't seem to be recognised as a rule as it's unreleased [here](https://dart-lang.github.io/linter/lints/require_trailing_commas.html).

Is this rule not available to be used yet or am I missing something?

**Comment by TheGlorySaint** [comment] 2021-12-04 15:59
@jackforesightmobile Hope you found your solution, if not

in your analysis_options.yaml add
`require_trailing_commas: true`
then save the file.

**Comment by SeasonLeee** [comment] 2021-12-06 16:04
@TheGlorySaint Hi, is this lint only work at VSCode? I am using Android Studio and I am also having this issue where I can't seem to have this lint working in my project, meaning there's no warning report to code like this:

```dart
body: const Center(child: Text('Hello World')),
``` 

Is there anything else I have to do to have this lint working? Or maybe it's because this [PR](https://github.com/dart-lang/linter/pull/2566) is being blocked that I can't have this lint working as expected? 

<details>
  <summary>And here's `my flutter doctor -v`</summary>
  
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale
    en-US)
    • Flutter version 2.5.3 at /Users/benjaminli/software_dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/benjaminli/Library/Android/Sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/benjaminli/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,LOCALHOST
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
</details>

And yes, I have turn on the lint in my analysis_options.yaml file.

I just can't have it... help....

**Comment by TheGlorySaint** [comment] 2021-12-06 16:16
@SeasonLeee Did you added

`flutter_lints: ^1.0.4` to the DEV_Dependencies? 
With your example I do not get the Trailing Comma annotation. 

Please try it with Following(longer) Code
`@override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text(
            'E-Mail Verifizieren',
          ),
        ),
        body: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: const [
            Center(
              child: Text(
                'Damit du mit deiner Registrierung weiter machen kann, musst du deine E-Mail-Adresse verifizieren. Dazu wurde an deine angegebene E-Mail-Adresse ein Link mit Anweisungen geschickt.',
              ),
            ),
          ],
        ));//Here should be the Trailing Comma
  }
`

**Comment by SeasonLeee** [comment] 2021-12-06 16:50
@TheGlorySaint 

Thank you so much for your advice on that package version there. I bumped the version to 1.0.4 and now I get the pertinent warning but it's not the way I expected, which I will report to that pr

So, now I get the warning only if the comma is missing like this:
![image](https://user-images.githubusercontent.com/13610283/144886892-494f5ce8-a9b8-4bc5-ae05-ad4f2217e13d.png)

But I thought it should have waring when there's double right round bracket like this:
![image](https://user-images.githubusercontent.com/13610283/144887231-a35d5bad-055c-4a34-b573-ba200f66a35a.png)

hmm... I'm not sure if it's by designed or anything... But I will raise this doubt to that PR anyway, thanks again!😄

**Comment by TheGlorySaint** [comment] 2021-12-06 16:56
@SeasonLeee Your Welcome, that my Answer helped you to get it running.

How I understood the Trailing Comma is working, it is the length of the Line and a few "Logical" Commas like your first Screenshot.

But at the second screenshot the length is fine(for the Trailing Comma) but logically there should be another Trailing Comma after the Text Widget String and I think the Logic isn't far or good enough to Support that feature for that.

**Comment by kuhnroyal** [comment] 2021-12-06 16:59
> But at the second screenshot the length is fine(for the Trailing Comma) but logically there should be another Trailing Comma after the Text Widget String and I think the Logic isn't far or good enough to Support that feature for that.

The 2nd condition is that there is only one parameter. Both screens look correct.

**Comment by SeasonLeee** [comment] 2021-12-06 17:04
😅 okay, after seeing what you guys talking about the triggering logic, I did a test. And now I think we may have some linter triggering issue😂, check this out:
![image](https://user-images.githubusercontent.com/13610283/144889461-38b8668b-b03e-4025-a6e3-a5d1889c574c.png)

@TheGlorySaint @kuhnroyal

**Comment by kuhnroyal** [comment] 2021-12-06 17:06
Then the condition is one named parameter, didn't remember exactly :)
