### ISSUE TITLE
Extension type methods can't be used in constant expressions

### ISSUE THREAD

**Issue by rainyl** [dart-lang/linter#5028] opened 2024-07-19 07:55 UTC
**Describe the issue**
lint error for `extension type` via `import as`

**To Reproduce**

```dart
// foo.dart
extension type const A(int value) {
  static const int C = 0;
  static const int D = 1;
  static const int E = 2;
}
```

```dart
// bar.dart
import 'foo.dart' as foo;

void main(List<String> args) {
  final v = switch (2) {
    foo.A.C || foo.A.D => 1,
    _ => -1,
  };
  print(v);
}
```

```bash
dart analyze .\bar.dart
```

output:

```bash
Analyzing bar.dart...

  error • bar.dart:5:5 • Extension type methods can't be used in constant expressions. •
          const_eval_extension_type_method
  error • bar.dart:5:16 • Extension type methods can't be used in constant expressions. •
          const_eval_extension_type_method

2 issues found.
```

**Expected behavior**

no errors 

**Additional context**

Windows 11

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (6 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

No errors with Flutter 3.19.6

**Comment by eernstg** [comment] 2024-07-19 08:11
I don't see those errors when using the bleeding edge version of the analyzer (from 9664f0da3547ccd92cf56d2bf362e333edfefd92), nor with version 3.6.0-12.0.dev, nor with 3.3.0-197.0.dev, which is older than the version you're mentioning.

I thought this would be a bug that has been fixed in a recent version, but that doesn't seem to be the case. Could your installed Dart toolchain have been damaged somehow?

In any case, `foo.A.C` denotes a constant variable and not a method so we should not have the error messages that you report.

**Comment by eernstg** [comment] 2024-07-19 08:52
OK, it does reproduce with `flutter analyze`, version 'Flutter 3.22.3'. Also, it does reproduce when executing the `dart` tool which is delivered with flutter

```
> /usr/local/google/home/eernst/bin/flutter_current/flutter/bin/cache/dart-sdk/bin/dart analyze bar.dart
Analyzing bar.dart...                 0.4s

  error • bar.dart:8:5 • Extension type methods can't be used in constant
          expressions. • const_eval_extension_type_method
  error • bar.dart:8:16 • Extension type methods can't be used in constant
          expressions. • const_eval_extension_type_method

2 issues found.
```

This implies that it is a flutter issue, or an issue which is caused by the creation of the `dart` executable in the Flutter release.

@chingjun, perhaps you could help finding the right person who'd know about the creation of a Flutter release?

**Comment by rainyl** [comment] 2024-07-19 08:54
> I thought this would be a bug that has been fixed in a recent version, but that doesn't seem to be the case.

Yes, I have just tested on beta channel (3.23.0-0.1.pre) and everything was ok, but it exists on stable channel (3.22.2 and 3.22.3), both on windows and linux. 

<details>
<summary>Linux 3.22.3</summary>

![image](https://github.com/user-attachments/assets/c866eb2a-be15-4fa7-8b6f-a10014cf5953)

</details>

<details>
<summary>Windows 3.22.3</summary>

![image](https://github.com/user-attachments/assets/742846f4-4bcf-46db-9910-85fbbb94345e)

</details>

<details>
<summary>Windows 3.23.0-0.1.pre</summary>

![image](https://github.com/user-attachments/assets/51b56adf-0b81-4bf1-8930-bb1ad03d8a75)

</details>

> Could your installed Dart toolchain have been damaged somehow?

Unlikely, I have already re-installed flutter

> In any case, foo.A.C denotes a constant variable and not a method so we should not have the error messages that you report.

I know that it should be a variable rather than a method, that's why I open this issue.

**Comment by eernstg** [comment] 2024-07-19 09:08
> I know that it should be a variable rather than a method, that's why I open this issue.

Of course. I spelled it out because these things can be tricky. In particular, non-local variables will implicitly induce a getter (and a setter, if mutable or `late final` without an initializer), and we do have the notion of a "getter function" and even a "getter method" in the language specification (it's rare, but it does occur). So it isn't unthinkable that the constant variable could be considered to denote a "method". It would be a bug, but that might be a place to look for the reason why we have this bug.

In any case, version 3.4.4-stable of the tool chain _does_ show the buggy behavior, even though various version before and after do not.

This means that it doesn't have anything to do with the creation of the Flutter release after all.

But it also means that it was a bug which was fixed.

**Comment by rainyl** [comment] 2024-07-19 09:16
Yes, anyway it disappears in later version, and it just a liner issue, the code just works fine.

BTW, this only happens with `import as`, no errors in the following code:

```dart
// bar.dart
import 'foo.dart';

void main(List<String> args) {
  final v = switch (2) {
    A.C || A.D => 1,
    _ => -1,
  };
  print(v);
}
```

**Comment by eernstg** [comment] 2024-07-19 09:21
Good to know, thanks!

@scheglov, it looks like there is a bug in 3.4.4 stable that causes the analyzer to report an error when a prefix-imported constant static variable in an extension type is used in a constant expression.

This issue serves as a reminder that it is a known issue, and it also mentions that this bug has been fixed in more recent versions. Do we have something like a list of known issues with specific released versions where we should include this issue?

**Comment by srawlins** [comment] 2024-07-19 13:45
This should be fixed with https://dart-review.googlesource.com/c/sdk/+/374900

> Do we have something like a list of known issues with specific released versions where we should include this issue?

I don't know of any such list.

**Comment by eernstg** [comment] 2024-07-19 13:58
Thanks, @srawlins!

Then I'll close this issue: It has been resolved, and the fix will arrive in a released version relatively soon.

**Closed by eernstg** 2024-07-19 13:58 UTC
