### ISSUE TITLE
Add lint for missing `await` when returning a value inside a `try` / `catch` block

### ISSUE THREAD

**Issue by cubuspl42** [dart-lang/linter#2946] opened 2021-09-13 09:11 UTC
**Describe the rule you'd like to see implemented**

I'd love to have a lint that detects missing `await` keyword  after `return` in `try` / `on` / `catch` blocks of `async` functions.

Without the `await` keyword in the `try` block, the `on` / `catch` block is ineffective.

**Examples**

```dart
class _Exception {}

Future<bool> foo() async {
  throw _Exception();
}

Future<bool> bar() async {
  try {
    print("Calling foo...");
    return /* await */ foo();
  } on _Exception catch (e) {
    print("We're all good! Exception $e is handled.");
    // ...except it's not handled at all, because of the missing `await`
    return false;
  }
}
```

**Additional context**

This problem caused the customer-affecting bug in `flutterfire` / `cloud_functions`  (https://github.com/FirebaseExtended/flutterfire/issues/2069).

It also broke my team's app yesterday.

**Comment by bwilkerson** [comment] 2021-09-13 15:07
Does the [`unawaited_futures`](https://dart-lang.github.io/linter/lints/unawaited_futures.html) lint satisfy this need?

**Comment by stuartmorgan** [comment] 2024-06-06 17:20
This is a lint that we would find very valuable for flutter/packages; we've had this bug a number of times across various packages, and a lint for it would be very useful.

**Comment by srawlins** [comment] 2024-06-28 15:39
Duplicate of https://github.com/dart-lang/linter/issues/2357, which has more context and discussion as well.

**Closed by srawlins** 2024-06-28 15:39 UTC
Labels: type-enhancement, lint-request
