### ISSUE TITLE
proposal: no constructor should give const suggestion?

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/linter#5014] opened 2024-07-06 10:31 UTC
moving from:
```
class _FalseColorSwitch extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
``` 
to 
```
class _FalseColorSwitch extends StatelessWidget {
  const _FalseColorSwitch(); // adding a const constructor that does nothing

  @override
  Widget build(BuildContext context) {
``` 
give me so many linter optimization suggestions:
```
Use 'const' with the constructor to improve performance.
Try adding the 'const' keyword to the constructor invocation.
``` 

I think no constructor should give me the same recommendation as a const constructor that does nothing. is there an actual difference?

**Comment by srawlins** [comment] 2024-07-08 15:47
Thanks for the clarification 👍

**Comment by srawlins** [comment] 2024-07-08 15:50
Looks like a duplicate of https://github.com/dart-lang/linter/issues/3983 and https://github.com/dart-lang/linter/issues/4717.

**Comment by stephane-archer** [comment] 2024-07-08 20:03
I think it's a duplicate too, thanks for pointing out existing issues.

**Closed** 2024-07-08 20:03 UTC
