### ISSUE TITLE
Analyzer gives confusing directions (`combinators_ordering`)

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/linter#4897] opened 2024-02-28 21:53 UTC
Given the following code:

```
import 'dart:io' as io show Directory, exitCode, Platform, stderr;
```

The analyzer will complain:

```
   info - engine_tool/lib/main.dart:6:24 - Sort combinator names alphabetically. Try sorting the combinator names alphabetically. - combinators_ordering
```

But the names are sorted alphabetically. 

The fix:

```
import 'dart:io' as io show Directory, Platform, exitCode, stderr;
```

seems wrong as it isn't alphabetically sorted (P comes after e).

The analyzer should be specific that it wants you to sort according to the ascii/utf-8 value of the characters.

**Comment by bwilkerson** [comment] 2024-02-28 22:02
Or the lint should be changed to use a case-insensitive comparison.

@pq

**Comment by pq** [comment] 2024-02-29 00:41
I'd be in favor of case-insensitive comparison in this case.

**Comment by johnmccutchan** [comment] 2024-02-29 01:49
making that change will probably cause a bunch of existing code to be out of spec?

**Comment by pq** [comment] 2024-02-29 02:46
It may very well. We'd want to do a bit of testing to measure impact first.

**Comment by srawlins** [comment] 2024-04-29 20:57
Duplicate of https://github.com/dart-lang/linter/issues/3866

**Closed by srawlins** 2024-04-29 20:57 UTC
Labels: type-bug, P4, type-ux
