### ISSUE TITLE
One or more rules that hint if members are not in order

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#698] opened 2017-06-09 07:13 UTC
with an order that matches the order "sort members" creates

https://github.com/dart-lang/linter/issues/696#issuecomment-307161591

**Comment by srawlins** [comment] 2024-08-01 21:10
Closing as duplicate of https://github.com/dart-lang/linter/issues/2367, which is newer but has more discussion.

**Closed by srawlins** 2024-08-01 21:10 UTC
Labels: type-enhancement, lint-request
