### ISSUE TITLE
use_build_context_synchronously and try/catch

### ISSUE THREAD

**Issue by slavap** [dart-lang/linter#3466] opened 2022-06-17 03:02 UTC
No warning in that case, though it should be:
```dart
try {
  await aaa(); // SUCCESS
  await bbb(); // FAILURE
} catch (ex, stack) {
  await ccc(context);
}
```

**Comment by srawlins** [comment] 2022-06-29 18:09
CC @goderbauer

**Comment by srawlins** [comment] 2022-11-07 18:33
Oops I think a duplicate of https://github.com/dart-lang/linter/issues/3028

**Comment by pq** [comment] 2022-12-14 21:59
Yep.  This is a dup.  Closing in favor of #3028.

**Closed by pq** 2022-12-14 21:59 UTC
Labels: type-bug, P2, false negative, set-flutter
