### ISSUE TITLE
deprecate / remove `prefer_bool_in_asserts`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1266] opened 2018-11-18 14:04 UTC
Since `prefer_bool_in_asserts` is obsolete in Dart 2, we should minimally document it as such.  Once we have a process for deprecation (#1179)  and removal, we should go ahead with that too.

**Comment by srawlins** [comment] 2018-11-20 16:08
Duplicate of #1220

**Closed** 2018-11-20 17:10 UTC
Labels: docs, enhancement
