### ISSUE TITLE
Should the two new "obvious"/"non-obvious"-concerned rules also target fields and top-level variables?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#5101] opened 2024-09-30 16:35 UTC
Effective Dart has a rule, ["DO type annotate fields and top-level variables if the type isn't obvious"](https://dart.dev/effective-dart/design#do-type-annotate-fields-and-top-level-variables-if-the-type-isnt-obvious). We have two new lint rules:

* [omit_obvious_local_variable_types](https://dart.dev/tools/linter-rules/omit_obvious_local_variable_types) and
* [specify_nonobvious_local_variable_types](https://dart.dev/tools/linter-rules/specify_nonobvious_local_variable_types)

(Effective Dart also has ["DON'T redundantly type annotate initialized local variables"](https://dart.dev/effective-dart/design#dont-redundantly-type-annotate-initialized-local-variables) which the new  rules conflict with; noted.)

Would it be a gain for users, and a gain for maintainability and complexity, to change the two new lint rules to also concern themselves with top-level variables and with fields?

Note that the Effective Dart rule does not distinguish between public and private:

> This rule applies to both public and private declarations. Just as type annotations on APIs help _users_ of your code, types on private members help _maintainers_.

(The Effective Dart rule is _sort of_ backed by an existing lint rule, [type_annotate_public_apis](https://dart.dev/tools/linter-rules/type_annotate_public_apis), but note that that lint rule _only_ reports on public API.)

CC @munificent @eernstg

**Comment by srawlins** [comment] 2024-09-30 16:38
The alternatives to _not_ expanding the two new lint rules, are:

* write additional sister rules, "omit_obvious_property_types" and "specify_nonobvious_property_types", to back the "DO type annotate fields and top-level variables if the type isn't obvious" Effective Dart rule, or
* punt on backing the "DO type annotate fields and top-level variables if the type isn't obvious" Effective Dart rule with a lint rule.

**Comment by srawlins** [comment] 2024-09-30 16:43
A benefit of separating out the concern of top-level variables and fields into different lint rules is a consistent set of rules that back Effective Dart. Internal Google might appreciate that, and continue to use the older [omit_local_variable_types](https://dart.dev/tools/linter-rules/omit_local_variable_types) rule.

**Comment by eernstg** [comment] 2024-10-01 08:48
Creating a couple of new lints would make a lot of sense! The fact that local variables and static/top-level variables have different dependency relations to other parts of the given software system already gives a strong hint that they might be treated differently by developers/organizations for good reasons.

I think it should be possible to reuse [hasObviousType](https://github.com/dart-lang/sdk/blob/eae93ca8272f41b47682d02d8085434a7a928444/pkg/linter/lib/src/util/obvious_types.dart#L93) directly. It does give an identifier that denotes a local variable a special treatment, and that case will never be reached when asking whether the declared type of a static/top-level variable is obvious. That shouldn't create any difficulties or wrong outcomes, it will only give rise to a tiny bit of wasted work (when we're testing whether an identifier denotes a local variable, and the outcome is always 'false').

> (Effective Dart also has ["DON'T redundantly type annotate initialized local variables"](https://dart.dev/effective-dart/design#dont-redundantly-type-annotate-initialized-local-variables) which the new rules conflict with; noted.)

I don't think it needs to be seen as a conflict.

In particular, we don't have to interpret 'redundantly' strictly as "the type annotation specifies the same type as the one that inference would have provided if the type annotation had not been there".

If the type annotation makes the code more readable for a human reader then I would not consider it to be redundant (and in that case I honestly don't care that those two types are identical, if the human reader needs to know the type, and it is not readily available).

Another case is when subtle changes in the typing of other expressions in the same function body cause the code to have inscrutable compile-time errors, or (worse) wrong behavior at run time. A well-placed type annotation on a local variable could make the code more robust against said subtle changes: Perhaps you don't get the wrong behavior in the first place, or you get a compile-time error rather than a silent propagation of subtly different types to many locations in this function body. Such a well-placed type annotation can make the code more robust when subjected to evolution of the software that it depends on (especially if it's in a different package, maintained by a different group of people). In short, the type annotation makes certain assumptions in the code explicit because we'd like to either confirm that they still hold, or we'd like to hear about it if they don't. Again: Not redundant, because it is a non-zero loss for developers who are managing code over time, if the type annotation is removed.

The whole point in having `omit_obvious_local_variable_types` is that it allows developers to omit type annotations on local variables whenever they want, and it nudges them to do so when the type is "obvious", but it provides a certain amount of wiggle room such that developers can include the occasional type annotation because they _don't_ think it's redundant.

**Comment by eernstg** [comment] 2024-10-02 10:14
https://dart-review.googlesource.com/c/sdk/+/387960 implements those lints (they're not very different from the `_local_variables` version of the same lints). One difficulty came up, though: `specify_nonobvious_property_types` should _not_ flag an instance variable with no type annotation if that type annotation is obtained by override inference.

```dart
class A {
  final num x = 1;
}

class B implements A {
  final x = 2.5; // OK, and it has type `num`.
}
```

How would the lint detect this?

**Comment by srawlins** [comment] 2024-10-02 14:54
> How would the lint detect this?

Yeah, tricky. If I understand the problem, we kind of need to know whether `A.x` has an _explicit_ type annotation. But A might be declared in a different library, such that we only have summary data, which I don't think would contain info about whether a field declaration has an explicit type. (Maybe we could add that.) Also, `B.x` could be overriding a getter/setter pair, and the components of the getter/setter pair may be declared / typed in different places in the hierarchy.

This is in particular interesting because of the proposed `override` keyword, yes?

**Comment by srawlins** [comment] 2024-10-02 14:56
@eernstg I don't know if you have a round-up of folks who's opinions is driving your `omit_obvious_local_variable_types` and
`specify_nonobvious_local_variable_types` rules,  but seeing as how you've uploaded https://dart-review.googlesource.com/c/sdk/+/387960, would it make sense to prioritize those rules too, and have all 4 available as experimental lint rules that flutter repositories in particular could dogfood?

**Comment by eernstg** [comment] 2024-10-03 10:09
> If I understand the problem, we kind of need to know whether A.x has an _explicit_ type annotation.

That's actually not necessary, we just need to know that `B.x` does not have an explicit type annotation, so `B.x` got its type from some implicit mechanism, and the mechanism that provided this type annotation was override inference.

However, it might not be that difficult after all: I do not think we have to retrace the algorithm that produced the given type annotation. That's a rather involved computation, and we don't need to compute that type. It would be sufficient to know that (1) there is no explicit type annotation, and (2) the declaration does not have a compile-time error. If we have that then I believe there is no other possibility than override inference. Also, we'd just ignore the declaration if it does have a compile-time error.

**Comment by eernstg** [comment] 2024-10-03 10:10
Right, I implemented this check and added a couple of tests, and it seems to work correctly.

**Comment by eernstg** [comment] 2024-10-03 10:10
> would it make sense to prioritize those rules too, and have all 4 available

Yes, indeed!

**Comment by denniskaselow** [comment] 2024-11-03 17:17
I don't know if I should open a new issue, but as it's still experimental, I'll add it here for now:

```dart
final Map<int, String> foobar = {};
```

This code gets flagged as:
> The type annotation isn't needed because it is obvious.

I just want to make sure if that's expected behavior when the generics are not specified on the right side of the assignment.

**Comment by eernstg** [comment] 2024-11-03 17:43
Right, if the type annotation is simply deleted then the type changes (and it's not a recommended typing because it has type arguments `<dynamic, dynamic>`). So we definitely don't want that.

However, the automatic fix operation that you can perform in some IDEs will not just remove the type annotation, it will add the type arguments to the map literal, yielding this:

```dart
final foobar = <int, String>{};
```

I think this style is quite useful (and it's been recommended by various members of the community): The type and value of the initializing expression is quite easy to see at a glance. With `final Map<int, String> foobar = {};` we'd have to look at the type annotation in order to see the type, and at the initializing expression in order to see the value.

Also, if you have several declarations of variables (all `final` or all `var`) whose type is "obvious" then you can have a nicely aligned column of names. So you might want to express the variable declarations such that they have an obvious type as often as possible.

Of course, you might prefer to have the type annotation more frequently (e.g., in _every_ variable declaration), but in that case you wouldn't enable `omit_obvious_property_types` in the first place.

However, I do agree that the lint message is a bit too terse in this case (it would have been nice if it could say that the actual type arguments should be moved from the left to the right, not just that the type annotation should be removed).

**Comment by eernstg** [comment] 2024-11-03 17:47
The lints `omit_obvious_property_types` and `specify_nonobvious_property_types` have been landed.

**Closed by eernstg** 2024-11-03 17:47 UTC
Labels: type-enhancement, lint-request
