### ISSUE TITLE
unnecessary_overrides does not catch cases in Flutter repository

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/linter#4400] opened 2023-05-27 00:19 UTC
Reproducible sample: The code just before https://github.com/flutter/flutter/pull/127480 lands.

**Comment by srawlins** [comment] 2023-05-29 04:39
Duplicate of https://github.com/dart-lang/linter/issues/4359

**Closed by srawlins** 2023-05-29 04:39 UTC
Labels: P3, false negative, set-core
