### ISSUE TITLE
Support custom lint rules

### ISSUE THREAD

**Issue by trentgrover-wf** [dart-lang/linter#697] opened 2017-06-08 22:06 UTC
I'd like to be able to specify custom lint rules outside of this package.  This is mostly to help enforce consistency in consumption patterns of some of our private libraries that don't apply well to the larger Dart community, but would be very beneficial to our developers.

To give 1 specific example, we've implemented a `Disposable` interface / mixin to assist with cleaning up streams and other data structures that won't necessarily be garbage collected without some manual intervention (https://github.com/Workiva/w_common).  I'd like to be able to perform some linting similar to the existing `cancel_subscriptions` and `close_sinks` rules to verify that any `Disposable` object instantiated is actually disposed.

**Comment by pq** [comment] 2017-06-20 17:47
cc @bwilkerson re: plugin support.

**Comment by kabiir** [comment] 2018-01-30 10:52
+1 👍 💯 Another example from me,
I want to impose myself and other devs involved in the project to always store DateTimes as MillisecondsSinceEpoch (int) and only use these DateTime Constructors : DateTime.utc(), DateTime.now() and DateTime.MillisecondsSinceEpoch. Mainly to maintain DateTime consistency throughout code.

**Comment by stt106** [comment] 2018-11-01 14:08
I think this would be an awesome feature to have! In some way, the customised linter can act like a second compiler which helps to detect more errors/code smell at compile time, leading to fewer runtime exceptions. 
Generally, OO compilers are less helpful in making illegal state impossible at compile, compared with FP compilers, mostly due to anything can be `null`. But with a customised linter, this would be improved a lot, having the benefits of both OO and FP worlds.

**Comment by stepancar** [comment] 2018-12-03 13:52
@pq Do you have any vision how to do plugins support? Why linter is a part of sdk now?
I can start research of this, but maybe you can share any information about discuss on this issue

**Comment by pq** [comment] 2018-12-10 14:22
Sorry for the slow reply @stepancar!  The original intention of the linter was for it to function as a plugin and be very loosely coupled w/ the SDK.  For a variety of reasons, largely performance-related, we had to step back from that.  (@bwilkerson can provide some more context.)

Anyway, I agree it would still be great to support some kind of model for pluggable analyses even if, for performance reasons, we need to keep the core linter embedded the way it is today.

Out of curiosity, what kinds of use cases are you envisioning?

**Comment by georgelesica-wf** [comment] 2018-12-10 18:31
We wrote an internal linter using the unsupported analyzer APIs that does the following right now:

  * enforce Flux events having a common base class that provides `Disposable` helpers
  * enforce Flux actions having a common base class (same reason)
  * require that Flux events and several other kinds of objects be "managed" (again, a `Disposable` thing)
  * we implemented our own `@NoImplement` annotation to prevent certain classes from being used as interfaces because doing so would make semver compliance more difficult
  * we implemented a `@Sealed` annotation to prevent overrides in certain cases

We've actually had some trouble porting this tool to Dart 2 because the analyzer has changed so much. At the time we wrote it, we met with @kevmoo and he indicated that a pluggable analyzer was coming. I know that became a thing for Flutter, but it isn't considered generally available and the documentation is very sparse, so it still doesn't help us (yet?).

I don't think we're picky about *how* we satisfy these use-cases, we just need to be able to satisfy them in a reasonably stable manner.

**Comment by pq** [comment] 2018-12-11 14:07
Thanks for the added context @georgelesica-wf!

When does your tool get run?  (And how regularly?)

Are you building on https://github.com/Workiva/dart_dev ?

FYI @bwilkerson

**Comment by trentgrover-wf** [comment] 2018-12-11 14:49
It's run by a global command: `pub global run dart_medic`

We can run that locally at will, but we also add it to our [dart_dev task runner](https://github.com/Workiva/dart_dev#task-runner-config) command and run it in CI.

**Comment by georgelesica-wf** [comment] 2018-12-11 15:22
To expand on your last question @pq it doesn't build on top of dart_dev directly. It actually does use our semver auditing tool as a library to get the compiled elements. Unfortunately, that's the part that has proven difficult to update to Dart 2.

**Comment by bwilkerson** [comment] 2018-12-11 15:39
> We've actually had some trouble porting this tool to Dart 2 because the analyzer has changed so much.

If there are specific questions about the analyzer APIs and how to update them, I'm more than happy to answer them for you. (The API is continuing to evolve to better represent the Dart 2.0 semantics and to allow for performance improvements in the implementation, and I might also be able to help you future-proof your code.) I'm happy to use any forum you want, but I'll see github issues and e-mail without prompting; for other forums you might need to let me know that there's something to respond to.

> At the time we wrote it, we met with @kevmoo and he indicated that a pluggable analyzer was coming. I know that became a thing for Flutter, but it isn't considered generally available and the documentation is very sparse, so it still doesn't help us (yet?).

Yes, we do have a plugin story for the analyzer now. It isn't Flutter specific, and Flutter isn't currently using it. It is currently being used to support Angular.

It's currently only being used by the analysis server, but we have (unscheduled) plans to add support for it to the command-line analyzer as well at some point.

We haven't made it generally available (encourages people to use it) because
* it isn't yet supported in the command-line analyzer,
* it's fairly heavyweight to use it (especially for something like a small number of fairly simple lint rules), and
* we haven't yet evaluated the performance characteristics of having large numbers of plugins running, so we don't know whether encouraging its use would hurt the UX.

I don't know when we might be able to address those concerns.

**Comment by cah4a** [comment] 2019-04-06 08:54
Any updates?

Custom rules could improve code consistency on a particular project.
Any well-coded project should have project-related conventions. The more convention checks are described as lint rules, the easier it's to follow these conventions.
It will save much time on a code review stage of each PR.

I think it's a must-have feature for any linter.

Also, it will allow to make a platform or framework specific rules. Flutter, Aqueduct or DartAngular rules could be very helpful.

**Comment by pq** [comment] 2019-04-06 13:11
@cah4a: no significant updates.  I'd still love to see this happen (for many of the reasons you describe and a few more).  Our current energy has been focussed on a scramble to keep up with (and support) [evolving Dart language features](https://github.com/dart-lang/language/projects/1) but continued conversation here (and upvotes) will help motivate prioritization down the road, so thanks for that!

Regarding convention checks, is it possible that some of your desired ones would be generally useful?  Are they worth considering implementing in the linter proper?

As for Flutter rules, could you enumerate ones you have in mind?  (Folks are actively thinking about those so your ideas will be especially welcome -- #142 is an old tracking issue too fwiw.)

Finally, short of tight integration of custom lints into the IDE could you see value in a way to run custom lints from a separate (command-line) tool?  A flow like @georgelesica-wf describes?

**Comment by jodinathan** [comment] 2019-04-06 13:40
Look at the scramble I guess overloaded functions is not in the near sight

Atenciosamente, 

Jonathan Rezende

**Comment by cah4a** [comment] 2019-04-06 17:11
@pq At the moment, I want to implement some "Separation Of Concerns" checks. Eg:
- No widgets outside "/widgets" folder
- No http requests outside "/api" folder
So it's not about what code does, but about where it exists. Don't think it could be generally useful.

Of course, I want to have custom lint rules because of tight IDE integration. So you could see those issues while you code. Otherwise, you try to satisfy CI after a commit is ready. That could be annoying.
If it's impossible, I will have to write my custom command with those checks as a workaround. 

As for flutter rules, I think the next could be useful:
- Provide child for AnimatedBuilder
- Redundant Column, Row, Stack
- Redundant StatefulWidget
- Dispose not called for ScrollController, AnimationController, GestureRecognizer, etc
- Don't call Navigation.push/pop in build
- Use EdgeInsetsDirectional/AlignmentDirectional/Positioned.directional for non-symmetric layouting

**Comment by pq** [comment] 2019-04-08 23:11
Thanks for the added context @cah4a.  Really helpful!

Adding @Hixie and @a14n as an FYI on flutter rule ideas.

**Comment by Hixie** [comment] 2019-04-12 22:58
See also https://github.com/flutter/flutter/issues/1220

**Comment by Levi-Lesches** [comment] 2019-09-20 16:57
Any progress on this? This seems like something that many users can benefit from.

**Comment by pq** [comment] 2019-09-21 14:56
Not much unfortunately.  Maybe once we're through extension methods and NNBD? 🤞 (That's the team-wide priority for the immediate term.)

**Comment by baiyingmh** [comment] 2019-12-26 03:20
Is there any progress on this, we need custom dart lint rules too, it is not universal for everyone, but it is a very meaningful constraint for our team's project

**Comment by bwilkerson** [comment] 2019-12-26 15:44
No, there hasn't been any progress on this. While extensions have shipped, NNBD is still very much our primary focus right now.

But more generally, I'm honestly not sure what support for custom lints would look like. Every time I think about what would be required in order to support custom lints I come to the same conclusion: it would look exactly like what we already support with analyzer plugins. Unless we could do something that would make it easier for users (and that can't be applied to the analyzer plugin support to also make it easier) I don't think we're likely to do anything different.

I generally discourage people from using our plugin support because we have not finished evaluating the impact that plugins have on the performance of the analysis server, nor are plugins used by the command-line analyzer.

The alternative is to write your own linter-like support using the analyzer package. It won't give you the IDE integration that analyzer plugins were designed to provide, but you could, at least, run them from the command-line and as part of your CI system.

**Comment by pq** [comment] 2019-12-26 15:56
Thanks Brian!

> The alternative is to write your own linter-like support using the analyzer package

If you do want to explore this route, you might find this package useful:

https://github.com/pq/surveyor

Adding custom analyses is what this is all about and it would be easy to create a script to run in a CI.

Feel free to reach out if you have any questions.

**Comment by winterDroid** [comment] 2020-02-04 23:18
Yeah I think it would be great to write custom rules as it is possible Android Lint. 

I had rules like the following in my mind:
- `Use Class X instead of Class Y`
- `Don't use Class X`
- `Classes extending X should be named like ...` 
- `Don't use Colors directly. Instead use MyColors`

Essentially very project setup specific rules that should help new team members to get onboarded and follow team internal rules.

**Comment by pq** [comment] 2020-04-08 17:49
Hey @LuisReyes98.  No significant updates.  Sorry!

**Comment by marcelgarus** [comment] 2020-04-09 12:12
I implemented a code-generator for [<kbd>has_is_getters</kbd>](https://pub.dev/packages/has_is_getters) and having lint rules that tell users to use `someObject.hasProporty` instead of `someObject.property != null` or `someObject.isEnumValue` instead of `someObject.someEnum == SomeEnum.value` would be really cool.

**Comment by LuisReyes98** [comment] 2020-04-09 23:54
Custom rules can also help keep order in big teams of programmers, giving errors when a class doesnt have comments for documentation for example

**Comment by mateusfccp** [comment] 2020-06-25 21:01
I'm making a _sumtypes_ package and it would be nice to make linter be able to extensively check for verification of subtypes like it already does with enum on switch.

Example:
```
@Sumtype
abstract class Rank { }

class Spades extends Rank { }
class Hearts extends Rank { }
class Clubs extends Rank { }
class Diamonds extends Rank { }

// ...
void rankSymbol(Rank rank) {
    final type = rank.runtimeType;

    // Here the linter would warn that Diamonds has not been checked
    switch (type) {
        case Spades:
            return '♠';
        case Hearts:
            return '♥';
        case Clubs:
            return '♣';
    }
}

**Comment by bwilkerson** [comment] 2020-06-25 21:26
> ... giving errors when a class doesnt have comments for documentation for example ...

This is an example of a generally useful lint that would be useful for lots of projects. (See https://dart-lang.github.io/linter/lints/public_member_api_docs.html).

**Comment by Levi-Lesches** [comment] 2020-06-25 22:03
> ...check for verification of subtypes like it already does with enum on switch.

My workaround for this is to give `Rank` an enum field. Like this: 
```dart
enum Suit {spades, hearts, clubs, diamonds}

abstract class Rank {
  Suit suit;
  Rank(this.suit);
}

class Spades extends Rank {
  Spades() : Rank(Suit.spades);
}
// other classes here

String getSuiteName(Rank rank) {
  switch(rank.suit) {
    case Suit.spades: return "spades";
    case Suit.spades: return "spades";
case Suit.spades: return "spades";

**Comment by mateusfccp** [comment] 2020-06-25 22:13
@Levi-Lesches Yeah, the problem is when the sumtypes has value. The example I gave was the most trivial possible, but there are cases where some of the values of the enum has "sub values".

Eg. `type List T = Nil | Cons T (List T)`

In these cases, I would do:

```dart
abstract class List<T> { }
class Nil<T> extends List<T> { }
class Cons<T> extends List<T> {
    final T value;
    final List<T> tail;
}
```

But I don't think if it is viable to use the enum approach in these cases.

**Comment by hpoul** [comment] 2020-06-25 22:37
@mateusfccp not really related to this issue, but you might want to take a look at how freezed implements it: https://pub.dev/packages/freezed#when .. i assume you already generate code, so you can workaround it by creating your own switch function with named arguments for each case.. with `@required` annotation this will trigger a warning if not passed along.

**Comment by mateusfccp** [comment] 2020-06-25 22:44
@hpoul Yeah, I already do it... I generate a `fold` function that takes 1 function for each of the sumtype variants... By doing this, I can force the programmer to provide each case...

The problem is to provide an `else` like case... I can make another parameter in `fold` providing the `else` case, but if I do this, then I will have to make all the other parameters optional. However, by doing this:
* I can't know when the user has exhaustively checked for all the variants *OR* provided the `else` case; or
* I make `else` obligatory and the user will have to provide an `else` case even if they checked for all the variants. 

Neither cases are good, but I think the second one is still better, and I think I'm going this way by now...

**Comment by marcelgarus** [comment] 2020-06-26 07:32
@mateusfccp 
That's why <kbd>freezed</kbd> has two different methods for that:
- `when`, which requires every variant to be specified and
- `maybeWhen`, which doesn't require all variants, but requires the `else` parameter.

Btw, I believe https://github.com/dart-lang/language/issues/349 might be interesting for you.

But IMO this discussion is getting out-of-scope for this issue.

**Comment by ykmnkmi** [comment] 2020-06-30 05:53
Anyone can write plugin for analyzer with [analyzer_plugin](https://pub.dev/packages/analyzer_plugin).
For example [angular_analyzer_plugin](https://github.com/dart-lang/angular/tree/master/angular_analyzer_plugin).

**Comment by nosmirck** [comment] 2020-09-04 16:05
I'd like to contribute with another idea, since Dart doesn't support interfaces (but implied interfaces) that doesn't stop anyone from extending a class (or abstract class) intended as an interface only.

If we had a linter that checks for an annotated class as `@interface` then the linter can take care of the rest and we can give whatever level of severity, either just a warning or make it a full blown error.

```dart
@interface
abstract class MyInterface extends OtherClass{  //Lint! interface must start with I, Lint! Interface cannot extend other classes
  int x; //Lint! Interface cannot declare instance fields
  void bar(){}; //Lint! interface cannot implement methods
}

//This interface is properly declared and can be used as expected
@interface
class IMyInterface{ 
  int get x;
  void bar();
}

class Foo extends IMyInterface{} //Lint! cannot extend an interface

//This class properly implements the interface
class Bar implements IMyInterface{
  int get x => 0;
  void bar(){
    print('hello');
  }
}
```

I might be missing more lints that we usually would have by using interfaces, but these are like the top most used features. This helps prevent developers of a library using a class that was intended as an interface to be extended.

**Comment by marcelgarus** [comment] 2020-09-05 17:26
@nosmirck Just a side note, not directly related to this issue: You can give classes private constructors to prevent them from being extended or instantiated in other files:
```dart
abstract class MyInterface {
  MyInterface._();
  ...
}
```

**Comment by chenenyu** [comment] 2020-09-29 08:40
Looking forward to this feature!  😭

**Comment by leecommamichael** [comment] 2020-10-11 16:43
@bwilkerson 
> No, there hasn't been any progress on this. While extensions have shipped, NNBD is still very much our primary focus right now.

Thank you for your hard work!

> But more generally, I'm honestly not sure what support for custom lints would look like. Every time I think about what would be required in order to support custom lints I come to the same conclusion: it would look exactly like what we already support with analyzer plugins. Unless we could do something that would make it easier for users (and that can't be applied to the analyzer plugin support to also make it easier) I don't think we're likely to do anything different.

I doubt many of us have tried using (or were aware of) analyzer plugins, so now I know to give that shot, thanks! There's no wonder it's hard to tell where this feature lands. Dart is broken up into _so many_ packages.

> I generally discourage people from using our plugin support because we have not finished evaluating the impact that plugins have on the performance of the analysis server, nor are plugins used by the command-line analyzer.

I think the community at-large should try this anyway. If we don't have people trying to use it, we may not understand the performance impact **or** the desired experience for creating linter plugins.

> The alternative is to write your own linter-like support using the analyzer package. It won't give you the IDE integration that analyzer plugins were designed to provide, but you could, at least, run them from the command-line and as part of your CI system.

From my perspective, there are so many tools in and adjacent-to the Dart SDK that it's hard to know which package/codebase to properly investigate for issues and solutions. I still can only guess how [pedantic](https://github.com/dart-lang/pedantic) works, probably a hard-coded list of privately defined lints inside of the analyzer? The repo has one `dart` file that's 90% comments.

I'm very thankful for the language support we have thus far. I'm _really_ looking forward to it catching up to being as developer friendly as ESLint. I'm no Javascript zealot, but I'm shocked at how much I missed auto-fix when working with Dart. There is a class of lints (I'd argue) that have one reasonable fix, so why report them at all? Why not just fix them? Things like `prefer_single_quotes`, `annotate_overrides`, `prefer_const_constructors` etc... I realize that functionally the linter should not be manipulating source-code but that's the experience I'm after.

**Comment by bwilkerson** [comment] 2020-10-11 17:24
Thanks for the thoughtful comments.

> I think the community at-large should try this anyway. If we don't have people trying to use it, we may not understand the performance impact or the desired experience for creating linter plugins.

That's probably true. If you do decide to give that path a try, please let us know how we could improve the support. As I said, it isn't being used much, as far as I know, so I'm sure there's lots of room for improvement.

> From my perspective, there are so many tools in and adjacent-to the Dart SDK that it's hard to know which package/codebase to properly investigate for issues and solutions.

That's totally understandable. But when you find such a problem you can [open an issue](https://github.com/dart-lang/sdk/issues/new) in the sdk repository and we'll be happy to route it to the correct team, including moving it to the correct repository if necessary. Please don't let the confusion of packages and repositories stop you from providing feedback or asking questions.

> I still can only guess how pedantic works, probably a hard-coded list of privately defined lints inside of the analyzer? The repo has one `dart` file that's 90% comments.

The `pedantic` package defines several versions of an analysis options file that users can `include` in their own analysis options file. This file encodes the lints that are enabled internally at Google (but not necessarily by either the Dart or Flutter teams). So, no, there's no hard coded list; all of the lint rules that you enable by using pedantic are included in the analysis options file that pedantic provides.

One of the internal decisions was to disallow the use of `ignore` comments. However, one lint rule (`unawaited_future`) has some valid exceptions that can't be statically accounted for, so it was decided that we should support using a special function (`unawaited`) as a way to silence that particular lint. Because it was introduced for internal use we decided to define it in the `pedantic` package, which is what's in that one dart file.

There's nothing special or magical about `pedantic` (other than the `unawaited` function, which probably should have been defined elsewhere). Anyone can publish their own set of lint rules for use by others.

> I'm no Javascript zealot, but I'm shocked at how much I missed auto-fix when working with Dart. There is a class of lints (I'd argue) that have one reasonable fix, so why report them at all? Why not just fix them? Things like `prefer_single_quotes`, `annotate_overrides`, `prefer_const_constructors` etc... I realize that functionally the linter should not be manipulating source-code but that's the experience I'm after.

I'm not aware of any plans to fix lints without user action, but we are looking at ways to make it easier to apply fixes than by applying each fix individually. Maybe not everything you're looking for, but hopefully a step in the right direction.

**Comment by leecommamichael** [comment] 2020-10-12 00:29
Thinking this is the right place for this; here are my thoughts after spending a couple hours getting an analyzer plugin working today.

Disclaimer: I have not managed to get it working yet, but I'm hopeful because my plugin appears (_and crashes!_) in the Analysis Server Diagnostics page. There's nothing here for me to go off of; to be fair, the documentation _did_ say they weren't easy to debug.
```
Unrecorded error while starting the plugin.
#0      new CaughtException.withMessage (package:analyzer/exception/exception.dart:51:47)
#1      new CaughtException (package:analyzer/exception/exception.dart:45:14)
#2      PluginSession.start (package:analysis_server/src/plugin/plugin_manager.dart:934:28)

#3      PluginInfo.start (package:analysis_server/src/plugin/plugin_manager.dart:210:42)
#4      PluginManager.addPluginToContextRoot (package:analysis_server/src/plugin/plugin_manager.dart:330:38)
#5      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:67:19)
```
Having written some editor extensions for VSCode, what I've read of the `analyzer_plugin` package feels natural in terms of declaring editor capabilities up-front in the plugin; in this case, declared by what mixins/methods your plugin has implemented. The manner of specifying edits is also familiar-seeming which is good, but I'll have to see what I think when I get it working.

It was a bit of a brain twist, _and I'll admit I drew a diagram_, to make sense of the package structure. This is new to me as my experience with Dart is writing Flutter applications and CLI scripts (not having developed a package for third-party use.)

I spent a fair amount of time looking through `built_value`'s usage of `analyzer_plugin`, but contradictory to the tutorial, none of their `analysis_options.yaml` declare a `plugin`. There was chatter referencing Angular's usage of analyzer_plugin, but all I found were dead-links to archived repositories. I _did_ find Angular's repo, but I haven't searched exhaustively for an analyzer plugin implementation.

I'm not aware of good examples to move with (built_value seems to be a bit against the grain of the tutorial). But at the end of the day, I've got the right structure 🤞 and it crashes.

**Comment by bwilkerson** [comment] 2020-10-12 15:29
> I spent a fair amount of time looking through `built_value`'s usage of `analyzer_plugin`, but contradictory to the tutorial, none of their `analysis_options.yaml` declare a `plugin`.

The tutorial probably didn't make this clear enough, but the `plugin` declaration needs to be added to the `analysis_options.yaml` file in any package (the target package) that depends on the plugin's host. Users of your package have to explicitly opt in to using your plugin.

> There was chatter referencing Angular's usage of analyzer_plugin, but all I found were dead-links to archived repositories. I did find Angular's repo, but I haven't searched exhaustively for an analyzer plugin implementation.

My understanding is that they have dropped support for the plugin.

> But at the end of the day, I've got the right structure 🤞 and it crashes.

You can pass the `--instrumentation-log-file=<path>` argument to the analysis server when starting it up. That will cause it to write information every time it receives requests from the client, sends responses or notifications to the client, sends requests to the plugins, or receives information from the plugins. That might contain more information about what's causing the plugin to crash.

**Comment by shyndman** [comment] 2020-10-12 17:02
Hey @leecommamichael and others,

I wanted to point out Moor's analyzer plugin as being a potentially useful example. They have a setup going where their plugin runs both as an analysis server plugin, and as a standalone binary (which makes testing pretty easy, presumably).

Plugin definition:
https://github.com/simolus3/moor/tree/master/moor/tools/analyzer_plugin

Implementation:
https://github.com/simolus3/moor/tree/master/moor_generator

There's a lot to go through, but it might help.

**Comment by fartem** [comment] 2020-11-15 08:08
@leecommamichael I ran into with same issue when my own plugin was starting on Dart Analyzer Server. In my case, solution was to change relative path in `pubspec.yaml` file in bootstrap package to absolute path (like from `../../` to `/Users/fartem/Projects/dart_analyzer_plugin`). [There](https://github.com/wrike/dart-code-metrics) is working plugin from Wrike, you can explore this plugin and find more information on getting started and working with the plugins API.

**Comment by SAGARSURI** [comment] 2020-11-18 07:59
Is there any update when this feature gonna land? We are expanding our team and now we want to have our own rules to maintain consistency across the team.

**Comment by pq** [comment] 2020-11-18 13:54
Hey @SAGARSURI.  Unfortunately, no.  It's something we've wanted to support for a long time but haven't had the resources to schedule.

**Comment by bwilkerson** [comment] 2020-11-18 18:05
I know I've said this before, but in the absence of an easier solution there are still two alternatives available to you:

1. You can write a stand-alone tool based on the `analyzer` package that will produce diagnostics. It's not ideal because users will have to run the tool manually and the results won't be integrated into IDEs or other workflows.

2. You could write a plugin using the `analyzer_plugin` package (which is built on top of the `analyzer` package). It's also not ideal because it's a non-trivial amount of work to get to where it's returning results, but it would then be integrated with both IDEs and the command-line analyzer (`dart analyze`).

**Comment by myryq** [comment] 2020-12-12 19:14
One more workaround, we can create custom analysis server snapshot with own rules, e.g lines_longer_than_120_chars

![image](https://user-images.githubusercontent.com/70189001/101992697-c7975000-3cbd-11eb-96c7-aa287e824bcb.png)

**Comment by bwilkerson** [comment] 2020-12-12 19:22
True. This has the disadvantage that you probably need to use APIs that we don't guarantee to continue supporting, but it does get you something that works. And because the command-line analyzer (`dart analyze`) uses the analysis server to get the analysis results, these will also show up there.

**Comment by nosmirck** [comment] 2020-12-13 20:59
> I know I've said this before, but in the absence of an easier solution there are still two alternatives available to you:
> 
> 1. You can write a stand-alone tool based on the `analyzer` package that will produce diagnostics. It's not ideal because users will have to run the tool manually and the results won't be integrated into IDEs or other workflows.
> 2. You could write a plugin using the `analyzer_plugin` package (which is built on top of the `analyzer` package). It's also not ideal because it's a non-trivial amount of work to get to where it's returning results, but it would then be integrated with both IDEs and the command-line analyzer (`dart analyze`).

Do you have an example for Option 2? I'd like to see an example of something simple so I can write my own, but so far I've not found any easy to follow instructions, not in the documentation or anywhere else.

**Comment by Liuzhiyang94** [comment] 2020-12-14 07:42
Is there any updates now ? I am going to make the Flutter project more international.

But the stuck job is how to scan the hard code of descrption, such as  ```Text("hello world")```
I have to generate a file to translate 'hello world' , but it's going to be  thounds of lines to check :(

If can custom lint rules,may be I can show  'warning' to remind me

**Comment by pq** [comment] 2020-12-14 14:58
> I am going to make the Flutter project more international.

A rule to help here may be general enough to merit an implementation in the linter proper.  Consider opening a feature request so we can discuss?

**Comment by bwilkerson** [comment] 2020-12-14 16:08
> Do you have an example for Option 2?

The only example I'm aware of is the plugin for the built_value package (https://github.com/google/built_value.dart/tree/master/built_value_analyzer_plugin).

**Comment by SixSheeppp** [comment] 2020-12-15 03:07
> > I am going to make the Flutter project more international.
> 
> A rule to help here may be general enough to merit an implementation in the linter proper. Consider opening a feature request so we can discuss?



> > I am going to make the Flutter project more international.
> 
> A rule to help here may be general enough to merit an implementation in the linter proper. Consider opening a feature request so we can discuss?

I create a line request.
Link: https://github.com/dart-lang/linter/issues/697#issuecomment-744496525

**Comment by Levi-Lesches** [comment] 2021-05-21 16:50
For what it's worth [Dart Code Metrics](https://github.com/dart-code-checker/dart-code-metrics) seems like it can help. Their `CONTRIBUTING.MD` file explains how to add a new rule, and you can also open an issue on their repo.

**Comment by bwilkerson** [comment] 2021-05-21 17:43
That's approximately the same amount of work that's required to add a lint to the `linter` package.

**Comment by fzyzcjy** [comment] 2021-07-22 07:59
any updates?

**Comment by hpoul** [comment] 2021-07-22 12:20
fwiw, using `analyzer_plugin` doesn't seem to be *that* complicated. I was able to [hack something working together in a few hours](https://github.com/hpoul/string_literal_finder/tree/master/packages/string_literal_finder#readme). (borrowed a few things from [dart-code-checker](https://github.com/dart-code-checker/dart-code-metrics/) and [cool_linter](https://github.com/jWinterDay/cool_linter/).

> but it would then be integrated with both IDEs and the command-line analyzer (dart analyze).

although this is unfortunately not correct, as plugins do not work with the CLI right now:

* https://github.com/dart-lang/sdk/issues/38407
* https://github.com/flutter/flutter/issues/28327#issuecomment-532875896

**Comment by pro100svitlo** [comment] 2021-09-30 13:54
~4 years but still no result ...

that's quite sad 😢

**Comment by btrautmann** [comment] 2022-05-12 14:48
> > I don't seem to be able to get the plugin working at all. If I enable the [analyzer instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) I see this:
> 
> Ah, interesting -- I was running into this last night in my other project trying to get things working and after I ran a `pub upgrade` I started seeing this issue. I'll move this over to an sdk issue and we can investigate further there.

Update: I do believe, as mentioned in https://github.com/dart-lang/sdk/issues/47567#issuecomment-1125086186, that flakiness was caused by using a relative path within the bootstrap package's pubspec. 

As far as this issue is concerned, our team was able to write our own analyzer plugin usable via CI and the IDE based on dart-code-metrics. Obviously this is a heavy-handed approach for _every_ team using dart/Flutter to do. Our team is _interested_ in possibly working on a way to make this easier for the community (dart code metrics has said they don't have interest in supporting custom lint rules), but we're not committed to it yet.

**Comment by incendial** [comment] 2022-05-12 15:32
> As far as this issue is concerned, our team was able to write our own analyzer plugin usable via CI and the IDE based on dart-code-metrics. Obviously this is a heavy-handed approach for every team using dart/Flutter to do. Our team is interested in possibly working on a way to make this easier for the community (dart code metrics has said they don't have interest in supporting custom lint rules), but we're not committed to it yet.

Dart Code Metrics here. Just to make it clear: out point is that a proper direction would be to have an easier way to create plugins rather than creating some additional package with api that depends on the plugins api. This approach is very fragile. Also, consider that if someone adds a linter rule to linter package or DCM, for instance, there will be no need for others to implement the same rule from scratch. Looks like a huge benefit for the community to me.

> dart code metrics has said they don't have interest in supporting custom lint rules

And to point it out clearly: DCM **is** a set of custom lint rules (among other features) and I'm really curious, what stops you from suggesting a rule and contributing instead of creating a whole new package?

**Comment by FMorschel** [comment] 2022-05-12 15:52
> And to point it out clearly: DCM is a set of custom lint rules (among other features) and I'm really curious, what stops you from suggesting a rule and contributing instead of creating a whole new package?

For me, the point of being able to create a package would be to develop project-specific rules. For example naming conventions, where the linter would aways tell me or someone in my team not to create `Manager`s, but to create `Controller`s instead

**Comment by incendial** [comment] 2022-05-12 16:03
> > And to point it out clearly: DCM is a set of custom lint rules (among other features) and I'm really curious, what stops you from suggesting a rule and contributing instead of creating a whole new package?
> 
> For me, the point of being able to create a package would be to develop project-specific rules. For example naming conventions, where the linter would aways tell me or someone in my team not to create `Manager`s, but to create `Controller`s instead

Event though I got the idea, looks like your case can be covered with a generic rule like https://dartcodemetrics.dev/docs/rules/common/ban-name. Or am I missing something?

**Comment by btrautmann** [comment] 2022-05-12 16:37
> And to point it out clearly: DCM is a set of custom lint rules (among other features) and I'm really curious, what stops you from suggesting a rule and contributing instead of creating a whole new package?

Yeah, along the same lines as what @FMorschel is saying above, we have project-specific rules based on internal APIs that we'd want to enforce, e.g use `MyNewApi` and not `MyOldApi` (and we'd want to do this based on the actual AST nodes themselves, not just naming) -- we even have a rule prohibiting the usage of "smart" (curly) apostrophes. 

I definitely apologize if I made it sound like DCM was "unwilling" or "rudely against" a more abstract solution. Definitely not my intention. Your project is awesome and helped us HUGELY with our own implementation. I _totally_ understand a desire not to build out a less-than-ideal solution like the one proposed above. I do think, though, that the "easier analyzer plugin" approach will probably be the only viable one for the foreseeable future. Out of curiosity, assuming you shipped as part of that solution a set of stable APIs that consumers could utilize, what are the exact concerns around fragility? Asking because it could inform (or deter us from) our approach.

**Comment by incendial** [comment] 2022-05-13 07:05
> I definitely apologize if I made it sound like DCM was "unwilling" or "rudely against" a more abstract solution. Definitely not my intention. 

Oh, no worries, I just tried to give an additional context for others.

> Your project is awesome and helped us HUGELY with our own implementation.

Thank you!

> I totally understand a desire not to build out a less-than-ideal solution like the one proposed above. I do think, though, that the "easier analyzer plugin" approach will probably be the only viable one for the foreseeable future. Out of curiosity, assuming you shipped as part of that solution a set of stable APIs that consumers could utilize, what are the exact concerns around fragility? Asking because it could inform (or deter us from) our approach.

Unfortunately, current plugins API is not that mature and sometimes has unexpected problems (mostly performance, but in early days we also copied some hacky code from Dart Angular plugin just to make ours work). I expect this kind of problems will resolve with time, especially if there will be more plugins (big thanks to the Dart team, they're really investing in making plugins great), but here are few examples of issue I'm talking about: https://github.com/dart-lang/sdk/issues/47851, https://github.com/Dart-Code/Dart-Code/issues/3679, https://github.com/dart-lang/sdk/issues/48682. If anything like that breaks, you might get your users become really unsatisfied with the stability of **your** package.

On the other hand there are some limitation from the API, like: no way to add custom `dart fix` contributions, no way to run plugin analysis on `dart analyze`, etc.

I think that's why investing in capabilities, stability, documentation / examples, and maybe some additional linting API for plugins might be a better approach, IMO.

If nothing of that stops you, take a look at this repo https://github.com/hisaichi5518/dart-linting. This might give you some ideas too.

**Comment by bwilkerson** [comment] 2022-05-16 14:27
> ... no way to add custom `dart fix` contributions ...

That is, unfortunately, true. It wouldn't be too hard, though, to add a protocol to support that case.

> ... no way to run plugin analysis on `dart analyze` ...

`dart analyze` is built on the analysis server, so it ought to be loading and running plugins. If that's not the case, then that's a bug. (As a reminder to myself: it's possible that `dart analyze` isn't waiting to get results from plugins before printing the results from server.)

**Comment by btrautmann** [comment] 2022-07-06 13:09
> Invertase published a package to make your custom lint rules: https://invertase.io/blog/announcing-dart-custom-lint 🎉
> 
> <img alt="image" width="1412" src="https://user-images.githubusercontent.com/24459435/177410353-3edf5ed2-4b7b-4965-b931-06796a1f3b9b.png">
> 
> cc: @rrousselGit

If I'm understanding how things work under the hood (I haven't looked at the source, but only the announcement blog post), this is very similar to what our team was thinking of doing, and probably has the risks that @incendial was warning about regarding building against an unstable API. That said, I think it's a great step in the right direction for the community at large and is the only reasonable next step at this time.

Our team ended up basically doing a pared own fork of dart code metrics, added the ability to baseline, and added the ability to parse/lint YAML files, which I don't think would be possible with Invertase's solution (at least out of the box). So for folks like us that want a more advanced feature set, it probably doesn't make sense to migrate, but for 99% of the community I think this is awesome!

**Comment by KKimj** [comment] 2022-07-06 13:37
> Invertase published a package to make your custom lint rules: https://invertase.io/blog/announcing-dart-custom-lint 🎉
> 
> <img alt="image" width="1412" src="https://user-images.githubusercontent.com/24459435/177410353-3edf5ed2-4b7b-4965-b931-06796a1f3b9b.png">
> 
> cc: @rrousselGit

Thanks!
What a terrific news!
I searched these custom linting functionalites for at least a year.

** Acknowledge invertase

**Comment by incendial** [comment] 2022-07-07 10:18
> and added the ability to parse/lint YAML files

@brianquinlan this sounds pretty lit 🔥 , we have the same in our roadmap

**Comment by rrousselGit** [comment] 2022-07-07 10:26
> added the ability to parse/lint YAML files, which I don't think would be possible with Invertase's solution

I don't see why you couldn't. custom_lint does it. When plugins are starting or fail to start, it underlines the plugin name in the project's pubspec.yaml

**Comment by btrautmann** [comment] 2022-07-07 11:44
> > added the ability to parse/lint YAML files, which I don't think would be possible with Invertase's solution
> 
> 
> 
> I don't see why you couldn't. custom_lint does it. When plugins are starting or fail to start, it underlines the plugin name in the project's pubspec.yaml

Totally, that's why I suffixed that statement with "(at least out of the box)" 😊

**Comment by bartekpacia** [comment] 2022-08-23 10:51
Would love to see some progress on this. It'd be really great if custom lint rules created with [custom_lint](https://pub.dev/packages/custom_lint) would be run with `dart analyze` (currently it's not possible).

**Comment by srawlins** [comment] 2024-09-30 16:14
Please follow https://github.com/dart-lang/sdk/issues/53402 for updates on the upcoming analyzer plugin system, which will provide the ability to write custom lint rules.

**Closed by srawlins** 2024-09-30 16:14 UTC
Labels: type-enhancement, P3
