### ISSUE TITLE
`depend_on_referenced_packages` triggers on endorsed federated plugins

### ISSUE THREAD

**Issue by LionChen-WORK** [dart-lang/linter#4098] opened 2023-03-01 07:41 UTC
**Describe the issue**

`depend_on_referenced_packages` triggers on endorsed federated plugins.

**To Reproduce**

1. Add dependency plugin `foo`.
   - e.g. [in_app_purchase](https://pub.dev/packages/in_app_purchase)
2. Import a federated plugin endorsed by `foo` 
    - e.g. [in_app_purchase_storekit](https://pub.dev/packages/in_app_purchase_storekit)
    - `import 'package:in_app_purchase_storekit/in_app_purchase_storekit.dart';`

**Expected behavior**

`depend_on_referenced_packages` not triggering.

**Comment by jakemac53** [comment] 2023-03-01 18:06
This is not an endorsed concept in pub or the ecosystem as a whole, and the lint is working as intended. I don't see any way it could support this unless we created an explicit mechanism for this pattern.

However, we already have an existing pattern that can be used for this purpose - exports. The `in_app_purchase` package can export the `in_app_purchase_storekit` package from any of its existing libraries, or a special one just for this purpose (ie: `package:in_app_store_purchase/in_app_store_purchase_storekit.dart`). This pattern will not trigger this lint.

**Comment by goderbauer** [comment] 2023-03-01 18:50
> CC @goderbauer could you say whether the above steps are the recommended (or only) way to use, for example, in_app_purchase_storekit?

@stuartmorgan can you speak to that?

**Comment by stuartmorgan** [comment] 2023-03-01 19:33
> the lint is working as intended

Agreed, and it's serving a valuable purpose here; I disagree with the OP that the expected behavior is it not triggering.

The only reason to import an implementation package that I know of is to use additional platform-specific API that's provided by that implementation package, and if you are doing that you absolutely *should* be depending on a specific version, because otherwise you're subject to breakage at any point.

> The `in_app_purchase` package can export the `in_app_purchase_storekit` package from any of its existing libraries

We could, but we've actually deliberately chosen not to. In part that's because we want the freedom to make breaking changes to platform-specific APIs (which generally are less frequently used that the main package's APIs) without also making a breaking change to the main package. Which is why the pattern this lint is warning against is, in fact, something that shouldn't be done as the lint says.

**Comment by jakemac53** [comment] 2023-03-01 22:21
The issue is that the `in_app_purchase_storekit` readme says "this package has been [endorsed](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#endorsed-federated-plugin), meaning that you only need to add in_app_purchase as a dependency in your pubspec.yaml.".

So yeah, that recommendation should be removed, if you want to allow breakages in that package. Otherwise there is no difference between recommending no dependency and directly exporting the package.

**Comment by stuartmorgan** [comment] 2023-03-02 01:39
I've filed https://github.com/flutter/flutter/issues/121757 to improve this.

> So yeah, that recommendation should be removed, if you want to allow breakages in that package (without breaking changes in your package).

It shouldn't be removed, it should be clarified. The problem isn't that it's wrong, it's that it's *sometimes* wrong. For the common case of plugin clients who are only using the app-facing APIs, the existence of the implementation packages as transitive dependencies rather than inline code is an implementation detail they shouldn't care about in general; that's the case that text was written for. However, we now have a pattern of doing platform-specific extensions in the implementation packages (rather than shoving all platform-specific details into the main plugin API, like plugins all had to do pre-federation), so there are now more cases where clients also care about the sub-packages which is where the current README is breaking down.

> So yeah, that recommendation should be removed, if you want to allow breakages in that package (without breaking changes in your package).

To the extent that the implementation packages are implementation details of the app-facing package, breaking changes to implementation packages without breaking changes to the app-facing package work just fine. We've done it already.

The intent was never for people to `import` the implementation packages without depending on them, it was (in the context the text was written in) describing a . That's just not always true any more.

> Otherwise there is no difference between recommending no dependency and directly exporting the package.

I think what's missing here is the understanding of what this README text was written in contrast to, which are unendorsed implementations. The way federated plugins work, you can add a dependency on an unendorsed implementation (`foo_someplatform`) of a plugin (`foo`), and still *only use APIs from `foo`*, which will now magically work on that platform. See [an early version of `file_selector_windows` for instance](https://pub.dev/packages/file_selector_windows/versions/0.0.2+1#usage). By contrast, with an endorsed package you don't need that dependency step in order to use `foo` APIs (thus the README text).

So yes, there is a difference: the same one as for any other package deciding whether or not to re-export its various dependencies (for which the answer is almost always no).

**Comment by jakemac53** [comment] 2023-03-02 16:30
Ah ok I think I understand now - as long as you never actually import the package yourself, you don't need the dependency. But there are some use cases where you do import it directly, in which case people do need to add the dependency, so that just needs to be called out?

**Comment by stuartmorgan** [comment] 2023-03-02 16:38
Correct.

**Comment by jakemac53** [comment] 2023-03-02 16:40
Ok, I am going to go ahead and close this issue then, as we all seem in agreement that it is doing the right thing.

**Closed by jakemac53** 2023-03-02 16:40 UTC
Labels: type-question, P2, set-core
