### ISSUE TITLE
unnecessary_null_comparison message is misleading

### ISSUE THREAD

**Issue by AbhishekDoshi26** [dart-lang/linter#5098] opened 2024-09-25 19:11 UTC
For the following code:
```
void main() {
  int? value;

  if (value == null || value! < 1) {
    print('null value');
  }
}
```
The variable `value` is always null. But the linter shows message "The operand can't be null, so the condition is always 'true'.
Remove the condition." which I feel is misleading.

I might be wrong in understanding the message.

<img width="852" alt="Screenshot 2024-09-26 at 12 39 02 AM" src="https://github.com/user-attachments/assets/4d852b95-7e07-4e0d-a797-734048770ace">

**Comment by srawlins** [comment] 2024-09-25 19:20
Thanks for the report. Duplicate of https://github.com/dart-lang/sdk/issues/53670, fixed recently.

**Closed by srawlins** 2024-09-25 19:20 UTC
