### ISSUE TITLE
Consider updating rules.json verification to sync w/ DEPS (not tip of tree)

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#4756] opened 2023-09-20 21:32 UTC
Currently we get the list of core, recommended and flutter lints from tip(s) of tree. This can cause build breakages in the SDK on unrelated changes (https://dart-review.googlesource.com/c/sdk/+/327023). It would probably be better if we tested against what's in the version of `package:lints` in DEPS. (Not sure what we want to do about flutter; @goderbauer?)

**Comment by goderbauer** [comment] 2023-09-20 21:48
For my own understanding, the breakages are caused by rules.json getting out of sync with core/recommended/flutter_lints on tip of tree? And rules.json is used to display the appropriate style badges on https://dart.dev/tools/linter-rules?

If the later is true, shouldn't it always use the lint set of the last stable release of package:lint/package:flutter_lints? The DEPS version my point to an unreleased WIP version (as it currently does) to dogfood an updated lint set in the SDK. It may be confusing if https://dart.dev/tools/linter-rules claims that a lint is in recommended, when in fact that hasn't been made available in a release?

**Comment by pq** [comment] 2023-09-20 21:53
Right. Good points. While better in some ways, preferring a published version still has the same problem where the SDK bots fall over because the world outside the SDK has changed (e.g., `package:lints` got published). With `DEPS`, at least we'd be able to correlate the breakage to an updated package.

The more general point though of what we're documenting on `dart.dev` is still worth discussing and I agree that what we're doing today is maybe a little odd and potentially confusing.

/fyi @parlough

**Comment by parlough** [comment] 2024-10-08 18:51
Closing as resolved by https://github.com/dart-lang/sdk/commit/e2a2761cc693f43587f3b803ce70a68405db336e which removes the inclusion of sets in the generated file.

**Closed by parlough** 2024-10-08 18:51 UTC
Labels: type-test, P2, area-build
